# Generated by Django 3.1.2 on 2020-11-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(max_length=100)),
                ('goods_number', models.IntegerField(null=True)),
                ('bought', models.BooleanField(null=True)),
            ],
        ),
    ]
